### ISSUE TITLE
When I try to run this on vercel, I get an error

### ISSUE THREAD

**Issue by OrangeThunderFire** [InterstellarNetwork/InterstellarAstro#2]
Build Failed
Command "pnpm run build" exited with 1

Status
Error
Environment
Production
Duration
1m 45s (2m ago)
Domains
[interstellar-astro-git-main-orangethunderfires-projects.vercel.app](https://interstellar-astro-git-main-orangethunderfires-projects.vercel.app/)
[interstellar-astro-2564jnsal-orangethunderfires-projects.vercel.app](https://interstellar-astro-2564jnsal-orangethunderfires-projects.vercel.app/)
Source
[main](https://github.com/OrangeThunderFire/InterstellarAstro/tree/main)
3b92156
Update README.md

**Comment by IncognitoTGT** [comment]
This version of interstellar will not work, it's still in early dev
